# Generated by Django 3.1.1 on 2020-09-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200906_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='age_limit',
            field=models.CharField(choices=[('12', '12'), ('18', '18')], max_length=2, null=True),
        ),
    ]
