# Generated by Django 3.1.1 on 2020-09-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200906_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='age_limit',
            field=models.IntegerField(choices=[('0', '0'), ('7', '7'), ('12', '12'), ('16', '16'), ('18', '18')], null=True),
        ),
    ]
