# Generated by Django 3.1.1 on 2020-09-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200906_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='countries',
            field=models.ManyToManyField(related_name='movies', to='core.Country'),
        ),
    ]
